### ISSUE TITLE
Error #3675: Texture format mismatch. in Starling

### ISSUE THREAD

**Issue by wanting252** [Gamua/Starling-Framework#680]
I use Starling 1.6 with Adobe AIR 17.0
And now this error just jumps from no place(previous version runs well). It happens before the AssetManager load done.

Can you please help me explain and guide me how to solve this? Ask if you need any more detail please.

**Comment by PrimaryFeather** [comment]
When you say "previous version runs well", do you mean the previous AIR or Starling version?
And are you using ATF textures or normal PNGs?

**Comment by wanting252** [comment]
I use normal PNGs(texture atlas uis.png and uis.xml) and with the previous Adobe AIR + Starling(before I use Starling 1.5.1 and Adobe AIR 16.x and it just runs ok). Now I update all version: Adobe AIR to 17.x  and Starling to 1.6.
+ The error happens only in Android, not IOS and Desktop.
+ In this line:
fromBitmapData(bitmap.bitmapData, generateMipMaps, optimizeForRenderToTexture, scale, format, repeat)
format = "bgra";
generateMipMaps = false;
optimizeForRenderToTexture = false;
scale = 2;
repeat=false;

**Comment by vpmedia** [comment]
Hi,
Adobe AIR SDK 17 + FP 17 is still in beta..

**Comment by PrimaryFeather** [comment]
Yes, please try it out with AIR 16 and Starling 1.6; that way, we can see if it's a Starling or an AIR problem. Thanks!

**Comment by wanting252** [comment]
You are correct! No error in Android with Thank @vpmedia @PrimaryFeather 
But if I remember correctly, last week I struggled with AIR 16.x on IOS because app crashed at start time with 64 bit ANE -_- And this problem is only solved with updating Adobe AIR 17.x.
This week I test my app in Android, and this happens... -_-
So should I use two sdks for different platforms? Hmm, I confused now -_-

**Comment by PrimaryFeather** [comment]
When are you planning to release the app? Perhaps AIR 17 is final when you reach the point where you're publishing the app. If that's possible, you could postpone the decision until then.

**Comment by eitho** [comment]
Hi,
Today I downloaded stable version of AIR17. But  I still have this problem on Android

There is my log:
ArgumentError: Error #3675: Texture format mismatch.
	at flash.display3D.textures::Texture/uploadFromBitmapData()
	at starling.textures::ConcreteTexture/uploadBitmapData()[/Users/nikolaytsoy/WorkPlace/work/ARBAuz/libs/starling/textures/ConcreteTexture.as:106]
	at starling.textures::Texture$/fromBitmapData()[/Users/nikolaytsoy/WorkPlace/work/ARBAuz/libs/starling/textures/Texture.as:256]
	at starling.textures::Texture$/fromData()[/Users/nikolaytsoy/WorkPlace/work/ARBAuz/libs/starling/textures/Texture.as:146]
	at Function/process()[/Users/nikolaytsoy/WorkPlace/work/ARBAuz/libs/starling/utils/AssetManager.as:800]
	at Function/http://adobe.com/AS3/2006/builtin::apply()
	at starling.utils::SystemUtil$/executeWhenApplicationIsActive()[/Users/nikolaytsoy/WorkPlace/work/ARBAuz/libs/starling/utils/SystemUtil.as:80]
	at Function/complete()[/Users/nikolaytsoy/WorkPlace/work/ARBAuz/libs/starling/utils/AssetManager.as:1043]
	at Function/onLoaderComplete()[/Users/nikolaytsoy/WorkPlace/work/ARBAuz/libs/starling/utils/AssetManager.as:1015]

**Comment by PrimaryFeather** [comment]
That's unfortunate. :disappointed: 
The same problem has been reported in the forum (in [this post](http://forum.starling-framework.org/topic/air-17-sdk-released?replies=10#post-77738)) — please check back with Fraggle and vote together on that bug. I'll contact Adobe, too, to make sure they fix this quickly. 

... with hindsight, I should have recommended to report this to Adobe right away. :pensive:

**Comment by neolit123** [comment]
i can't reproduce the bug with the textured hello triangle test from Adobe and AIR 17 on Android and the Win32 desktop:
http://www.adobe.com/devnet/flashplayer/articles/hello-triangle.html

tried::
- uploading a lot of 2048x2048 textures
- adding more vertices
- same mipmap generation method as Starling on / off
- baseline / baseline constrained
- optimizeForRenderToTexture on / off
- stencils on / off
- different texture formats (except ATF)
- switching on / off "linear / nearest", "repeat" flags for "tex" in the fragment program

but this could be a combination of parameters...

a tip to the reporting:
try to narrow down the cause by switching some settings in your project. unless Adobe are able to reproduce the bug, it can take quite some time for them to figure out why it happens.

**Comment by vpmedia** [comment]
Maybe try adb logcat, so check out android system logs..

**Comment by grosssmutttr** [comment]
I'm getting this issue too with Adobe AIR 17, feathers 1.3.1 and starling 1.5.1.
On a Nexus 4 with Android 5.0 it is working on a Samsung Galaxy S2 the error occurs...

Alos tested AIR 17 with the latest Starling 1.6 and feathers 2.1.1...same error and also only the S2 throws the error.

**Comment by PrimaryFeather** [comment]
This problem seems to be similar to [this one](https://github.com/Gamua/Starling-Framework/issues/676). There's an Adobe engineer listening in that thread (abhinavdhandh), please post your problem description over there, as well!

**Comment by dmpanis** [comment]
Same here, this is device related. Some devices that have this issue are:

HP Slate 10
Samsung galaxy 3 tablet
POLAROID Tablette 10,1"

Very urgent!!!

**Comment by caseyryan** [comment]
Same problem on samsung galaxy ace 3 with air 17. No problem on lenovo b6000 with the same air version though. That's very annoying...

**Comment by raedkhelfa** [comment]
same error on galaxy tab 2 10.1

**Comment by GameAccountNetwork** [comment]
Any update on this? I'm starting to get some heat from clients

**Comment by caseyryan** [comment]
It's an AIR 17 problem.  16th works perfectly

**Comment by raedkhelfa** [comment]
yea i got no problem in Air 16 .. its AIR 17 issue

**Comment by PrimaryFeather** [comment]
In issue #676, Adobe answered that they've found the problem and the fix will be part of the next release. Although I don't know yet if this includes error 3675 mentioned here.

**Comment by kyle1046** [comment]
same problem with the samsung galexy tablet 3 SM-T210R
works perfectly fine on samsung glaexy s5 but on tablet it throws a lot of errors from the source code not my code http://citrusengine.com/
the errors its throwing are as follows
<pre land="xml">ArgumentError: Error #3675: Texture format mismatch.
	at flash.display3D.textures::Texture/uploadFromBitmapData()
	at starling.textures::ConcreteTexture/uploadBitmapData()[/Users/redge/Dropbox/Development/starling/starling/src/starling/textures/ConcreteTexture.as:106]
	at starling.textures::Texture$/fromBitmapData()[/Users/redge/Dropbox/Development/starling/starling/src/starling/textures/Texture.as:256]
	at MiniBitmapFont$/get texture()[/Users/redge/Dropbox/Development/starling/starling/src/starling/text/MiniBitmapFont.as:279]
	at starling.text::BitmapFont()[/Users/redge/Dropbox/Development/starling/starling/src/starling/text/BitmapFont.as:89]
	at starling.text::TextField/set fontName()[/Users/redge/Dropbox/Development/starling/starling/src/starling/text/TextField.as:548]
	at starling.text::TextField()[/Users/redge/Dropbox/Development/starling/starling/src/starling/text/TextField.as:134]
	at StatsDisplay()[/Users/redge/Dropbox/Development/starling/starling/src/starling/core/StatsDisplay.as:45]
	at starling.core::Starling/showStatsAt()[/Users/redge/Dropbox/Development/starling/starling/src/starling/core/Starling.as:978]
	at Function/starling.core:Starling/showStatsAt/starling.core:onRootCreated()[/Users/redge/Dropbox/Development/starling/starling/src/starling/core/Starling.as:999]
	at starling.events::EventDispatcher/invokeEvent()[/Users/redge/Dropbox/Development/starling/starling/src/starling/events/EventDispatcher.as:145]
	at starling.events::EventDispatcher/dispatchEvent()[/Users/redge/Dropbox/Development/starling/starling/src/starling/events/EventDispatcher.as:117]
	at starling.events::EventDispatcher/dispatchEventWith()[/Users/redge/Dropbox/Development/starling/starling/src/starling/events/EventDispatcher.as:195]
	at starling.core::Starling/initializeRoot()[/Users/redge/Dropbox/Development/starling/starling/src/starling/core/Starling.as:453]
	at starling.core::Starling/initialize()[/Users/redge/Dropbox/Development/starling/starling/src/starling/core/Starling.as:426]
	at starling.core::Starling/onContextCreated()[/Users/redge/Dropbox/Development/starling/starling/src/starling/core/Starling.as:671]</pre>

**Comment by illuzor** [comment]
This bug is fixed in 18 beta.
http://labsdownload.adobe.com/pub/labs/flashruntimes/shared/air18_flashplayer18_releasenotes.pdf

**Comment by flashmandv** [comment]
It is NOT fixed in AIR 18 Beta..I'm using AIR 19 Final and is throwing the same error.
tried swf-version 27 - not working..swf-version 30 - also not working.
The problem happens with old phones/tablet with not enough RAM .
It happens on my HTC Desire HD with latest 4.14.1 SDK and AIR 19.

It is throws when I'm trying to set .width of starling Button.

**Comment by PrimaryFeather** [comment]
@flashmandv, please add that information to #676 - some Adobe engineers are watching that thread, and they are always looking for concrete information about such bugs. The more detailed the information you give them, the better. Thanks in advance!

**Comment by ZwickTheGreat** [comment]
Just received this error on Android with AIR 27.

manufacturer
HUAWEI

model
ALE-L21

osName
Android

osVersion
6.0

screenSize
720 x 1280
